version: '3.8'

services:
  alpine-python:
    image: alpine:latest
    command: tail -f /dev/null
    volumes:
      - sit_producer:/data  
    tty: true  
    container_name: sit-producer-container
    environment:
      - TZ=America/Detroit  
    networks:
      - alpine-net
    entrypoint: |
      /bin/sh -c "
      apk add --no-cache python3 py3-pip git;
      pip3 install pytz --break-system-packages;
      pip3 install kafka-python --break-system-packages;
      pip3 install python-dotenv --break-system-packages;
      if [ ! -d /data/LoadCell-Kafka ]; then
        git clone https://github.com/DevinMB/LoadCell-Kafka.git /data/LoadCell-Kafka;
      fi
      sleep 10;
      python3 /data/LoadCell-Kafka/kafka_sit_producer.py
      "

networks:
  alpine-net:
    driver: bridge

volumes:
  sit_producer:  
